# Generated by Django 6.0.2 on 2026-03-29 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your capsule a meaningful title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='What memories are you preserving?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateField(help_text='When should this capsule be opened? (Must be in the future)')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('private', 'Private - Only me'), ('shared', 'Shared - People I choose'), ('public', 'Public - Everyone')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('sealed', 'Sealed'), ('opened', 'Opened'), ('expired', 'Expired')], default='sealed', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='capsule_images/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text="Users who can view this capsule (if privacy is 'shared')", related_name='shared_capsules', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_capsules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_open_any_capsule', 'Can open any capsule regardless of date')],
            },
        ),
        migrations.CreateModel(
            name='CapsuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('memory', 'Memory Note')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='capsule_contents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='capsules.capsule')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]