# Generated by Django 6.0.2 on 2026-03-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='open_date',
            field=models.DateTimeField(help_text='When should this capsule be opened? (Must be in the future)'),
        ),
    ]
