# Generated by Django 6.0.2 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='status',
            field=models.CharField(choices=[('sealed', 'Sealed'), ('opened', 'Opened')], default='sealed', max_length=10),
        ),
    ]
